name: default
seed: 343
dir: girish
hydra:
    run:
        dir: ./${dir}/${name}/${experiment.dataset.name}/${experiment.fold}/${seed}/${experiment.task.name}/${experiment.logdir}/bs${experiment.batch_size}_lr${experiment.optimizer.args.lr}
        #_pbs${experiment.pretraining_bs}_plr${experiment.pretraining_lr}
    sweep:
        dir: ./${dir}/${name}/${experiment.dataset.name}/${experiment.fold}/${seed}/${experiment.task.name}/${experiment.logdir}/bs${experiment.batch_size}_lr${experiment.optimizer.args.lr}
        subdir: ./
work_dir: ${hydra:runtime.cwd}
data_dir: ${work_dir}/data/
defaults:
  - experiment: two_view_mnist_pretraining
  #- hydra/launcher: submitit_slurm
