# @package hydra.launcher
submitit_folder: $&#123;hydra.sweep.dir/.submitit/%j
timeout_min: 7200
cpus_per_task: 5
gpus_per_node: 1
tasks_per_node: 1
mem_gb: 44
nodes: 1
name: ${hydra.job.name}
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
partition: qTRDGPUH
comment: null
constraint: null
exclude: null
cpus_per_gpu: null
gpus_per_task: null
mem_per_gpu: null
mem_per_cpu: null
signal_delay_s: 120
max_num_timeout: 0
additional_parameters: {}
array_parallelism: 256
setup: null